#Deployment
###controllers/pb-deploy.tml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: petclinic-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic-app
  template:
    metadata:
      labels:
        app: petclinic-app
    spec:
      containers:
      - name: petclinic-container
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: petclinic-config
      - name: count-log-1
        image: busybox
        args: [/bin/sh, -c, 'tail -n+1 -F /var/log/petclinic.log']
        volumeMounts:
        - name: efklog
          mountPath: /var/log  
        emptyDir: {}
      imagePullSecrets:
      - name: loyalsecret


